/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.6.4/samples
 */
tasks.register("greeting") {
    description = "First greeting"
    group = "tutorial"
    doLast {
        println("Hello World!")
    }
}

tasks.register("do_some_work") {
    description = "Do some work"
    group = "tutorial"
    doLast {
        val work: () -> Unit = {
            println("Work Completed!")
        }
        work.invoke()
    }
}